<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Cours extends \App\Entity\Cours implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'captchaCode', '' . "\0" . 'App\\Entity\\Cours' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Cours' . "\0" . 'Nom_C', '' . "\0" . 'App\\Entity\\Cours' . "\0" . 'Date_C', '' . "\0" . 'App\\Entity\\Cours' . "\0" . 'Id_Co', '' . "\0" . 'App\\Entity\\Cours' . "\0" . 'image_cours', '' . "\0" . 'App\\Entity\\Cours' . "\0" . 'reservations'];
        }

        return ['__isInitialized__', 'captchaCode', '' . "\0" . 'App\\Entity\\Cours' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Cours' . "\0" . 'Nom_C', '' . "\0" . 'App\\Entity\\Cours' . "\0" . 'Date_C', '' . "\0" . 'App\\Entity\\Cours' . "\0" . 'Id_Co', '' . "\0" . 'App\\Entity\\Cours' . "\0" . 'image_cours', '' . "\0" . 'App\\Entity\\Cours' . "\0" . 'reservations'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Cours $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getCaptchaCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCaptchaCode', []);

        return parent::getCaptchaCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setCaptchaCode($captchaCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCaptchaCode', [$captchaCode]);

        return parent::setCaptchaCode($captchaCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNomC(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomC', []);

        return parent::getNomC();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomC(string $Nom_C): \App\Entity\Cours
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomC', [$Nom_C]);

        return parent::setNomC($Nom_C);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateC(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateC', []);

        return parent::getDateC();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateC(string $Date_C): \App\Entity\Cours
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateC', [$Date_C]);

        return parent::setDateC($Date_C);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdCo(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdCo', []);

        return parent::getIdCo();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdCo(string $Id_Co): \App\Entity\Cours
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdCo', [$Id_Co]);

        return parent::setIdCo($Id_Co);
    }

    /**
     * {@inheritDoc}
     */
    public function getImageCours(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImageCours', []);

        return parent::getImageCours();
    }

    /**
     * {@inheritDoc}
     */
    public function setImageCours(?string $image_cours): \App\Entity\Cours
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImageCours', [$image_cours]);

        return parent::setImageCours($image_cours);
    }

    /**
     * {@inheritDoc}
     */
    public function getReservations(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReservations', []);

        return parent::getReservations();
    }

    /**
     * {@inheritDoc}
     */
    public function addReservation(\App\Entity\Reservation $reservation): \App\Entity\Cours
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addReservation', [$reservation]);

        return parent::addReservation($reservation);
    }

    /**
     * {@inheritDoc}
     */
    public function removeReservation(\App\Entity\Reservation $reservation): \App\Entity\Cours
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeReservation', [$reservation]);

        return parent::removeReservation($reservation);
    }

}
