<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVDi4Eo6\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVDi4Eo6/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVDi4Eo6.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVDi4Eo6\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerVDi4Eo6\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'VDi4Eo6',
    'container.build_id' => '4f6ff9e2',
    'container.build_time' => 1650585895,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVDi4Eo6');
