<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJqMx3MX\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJqMx3MX/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJqMx3MX.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJqMx3MX\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerJqMx3MX\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'JqMx3MX',
    'container.build_id' => '2f7b6585',
    'container.build_time' => 1652225185,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJqMx3MX');
